version: '3'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/api
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  
  nginx:
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
    volumes:
      - ./:/srv/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
